### ISSUE TITLE
Single executable binary cpggen on Linux for a java app gives zero findings

### ISSUE THREAD

**Issue by ayshas112** [AppThreat/cpggen#10]
![image](https://user-images.githubusercontent.com/105374772/232129659-ea52c0a7-373a-4bf8-9c67-bb569250cc44.png)
![image](https://user-images.githubusercontent.com/105374772/232129680-a4c04f70-d4d7-4681-864d-b326011f9522.png)
![image](https://user-images.githubusercontent.com/105374772/232129709-77aa0160-39ae-419a-9244-c407b4dba174.png)

**Comment by prabhu** [comment]
@ayshas112 The error indicates that java2cpg.jar wasn't bundled correctly. Could you kindly retest with the latest version?

[cpggen-linux-amd64](https://github.com/AppThreat/cpggen/releases/download/v0.9.2/cpggen-linux-amd64)

**Comment by prabhu** [comment]
@ayshas112 could you kindly retest with the latest version for linux?

**Comment by ayshas112** [comment]
@prabhu , do I pick the latest binary for linux from here - https://github.com/AppThreat/cpggen/releases ?
