### ISSUE TITLE
cpggen errors out on windows, but displays a successful submission message in the end.

### ISSUE THREAD

**Issue by nishfath** [AppThreat/cpggen#11]
Executed the cpggen for windows. Errors out with proper messages, but shows a successful scan and submission towards the end.

 [WinError  1314WinError 1314[]1314]WinError  A required privilege is not held by the client: ] A required privilege is not held by the client: 
.
.
INFO     Error: Unable to access jarfile /usr/local/bin/java2cpg.jar 
.
.

           INFO     shiftleft-java-demo-java uploaded successfully

Complete logs attached
[cpggen-error-log.docx](https://github.com/AppThreat/cpggen/files/11264312/cpggen-error-log.docx)

**Comment by prabhu** [comment]
@nishfath could you kindly retest with the latest cpggen for windows?
