### ISSUE TITLE
how to export the cpg to some format that could be consumed by some tool 

### ISSUE THREAD

**Issue by soneyahossain** [AppThreat/cpggen#2]
Hello,

After installing the "cpggen" package with the command "pip install cpggen", I was able to generate cpg, it is stored in a ".bin.zip" file. I'm wondering how I can convert the graph into a different format, such as ".dot", which I can then use as inputs for my tool.

**Comment by prabhu** [comment]
@soneyahossain Please try version 0.8.0 which adds an argument `--export` to export the CPG.
