### ISSUE TITLE
Best fix scan recommendations does not work with cpggen

### ISSUE THREAD

**Issue by nishfath** [AppThreat/cpggen#9]
As we do not pass any arguments in the workflow for cpggen, how do we work on the scan recommendations provided by 'Bestfix' ?
As an example, I used cpggen for the app 'Fineract' and then executed bestfix for this app. The scan recommendation were as below.
How do we work on those scan recommendations? 

![image](https://user-images.githubusercontent.com/81247855/232123203-0a1db181-060d-4e21-a0ac-d7c1c7da495a.png)

**Comment by prabhu** [comment]
@nishfath Bestfix.ai currently doesn't recognize how the CPG gets generated. I will keep this as a requirement while working on an update.
